%% Import data from text file.
% Script for importing data from the following text file:
%
%    /mnt/bb/Beaglebone-Lil-Motor-C-Lib/data.txt
%
% To extend the code to different selected data or a different text file,
% generate a function instead of a script.

% Auto-generated by MATLAB on 2017/02/15 10:22:24

%% Initialize variables.
filename = '/mnt/bb/Beaglebone-Lil-Motor-C-Lib/data.txt';
startRow = 2;

%% Format string for each line of text:
%   column1: double (%f)
%	column2: double (%f)
%   column3: double (%f)
%	column4: double (%f)
%   column5: double (%f)
%	column6: double (%f)
%   column7: double (%f)
%	column8: double (%f)
%   column9: double (%f)
%	column10: double (%f)
%   column11: double (%f)
%	column12: double (%f)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%11f%12f%12f%12f%12f%12f%12f%12f%12f%12f%12f%f%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to format string.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, 'Delimiter', '', 'WhiteSpace', '', 'HeaderLines' ,startRow-1, 'ReturnOnError', false);

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.

%% Allocate imported array to column variable names
step = dataArray{:, 1};
cputime = dataArray{:, 2};
cputimediff = dataArray{:, 3};
angle = dataArray{:, 4};
ref = dataArray{:, 5};
error = dataArray{:, 6};
ierror = dataArray{:, 7};
derror = dataArray{:, 8};
pterm = dataArray{:, 9};
iterm = dataArray{:, 10};
dterm = dataArray{:, 11};
v = dataArray{:, 12};


%% Clear temporary variables
clearvars filename startRow formatSpec fileID dataArray ans;