// THIS FILE (sysfs-paths.h) IS AUTOMATICALLY GENERATED BY ./run.sh
#ifndef SYSFS_PATHS_H
#define SYSFS_PATHS_H
#define PWM_PATH "/"
#define GPIO_AIN1_PATH "/sys/class/gpio/gpio111/"
#define GPIO_AIN2_PATH "/sys/class/gpio/gpio112/"
#define GPIO_STBY_PATH "/sys/class/gpio/gpio110/"
#define EQEP_PATH "/sys/devices/platform/ocp/48302000.epwmss/48302180.eqep/"
#endif // header guard
